use walmart;
-- ----------------- --------------------------------------------------------------
-- 1 how many customers there are in terms of gender

select gender,
       count(invoice_id)
from walmart_sales
group by gender;

-- the type of customers in our table
select customer_type,
       count(invoice_id) as count
from walmart_sales
group by customer_type;

-- . how many branches there are and where they are located
SELECT DISTINCT branch,
       city
from walmart_sales;

-- The most used payment method
select payment_method,
       count(1) as count
from walmart_sales
group by payment_method
order by count desc;

-- the most sort after product line per gender
select gender,
       product_line,
       count(product_line) as count
from walmart_sales
group by gender, product_line
order by count desc;

-- most used payment method
select payment_method,
       count(payment_method) as count
from walmart_sales
group by payment_method
order by count desc;

-- revenue generated by sales
select round(sum(total), 2) as revenue
from walmart_sales;

-- revenue generated per branch
select branch,
       round(sum(total), 2) as revenue
from walmart_sales
group by branch
order by revenue desc;

-- revenue generated by each product
select product_line,
       round(sum(total), 2) as revenue
from walmart_sales
group by product_line
order by revenue desc;
-- percentage of sales per product line

select product_line,
       round(sum(total), 2) as revenue,
       CAST(SUM(total) * 100 / (select sum(total) from walmart_sales) as DECIMAL(10, 2) ) as pct
from walmart_sales
group by product_line
order by revenue desc;

-- number of products sold
select product_line,
       sum(quantity) as qty
from walmart_sales
group by product_line
order by qty desc;

-- most taxed product line
select product_line,
       avg(vat) as avg_tax
from walmart_sales
group by product_line
order by avg_tax desc
limit 1;

-- most expensive price item per product line
select product_line,
       round(max(unit_price), 0) as max_price
from walmart_sales
group by product_line;

-- least expensive price per product
select product_line,
       round(min(unit_price), 0) as max_price
from walmart_sales
group by product_line;

-- arange your database in form of product line
select w.invoice_id,
       w.branch,
       w.product_line,
       w.unit_price,
ROW_NUMBER () over(PARTITION BY product_line order by unit_price desc) as rn
from walmart_sales w;

-- display the first and last record of the database
select min(invoice_id) as firt_record,
       max(invoice_id) as last_record
from walmart_sales;